Month 9/step 2
Igor20099/react-burger pull request #6
Opened 2023-05-24 02:12 UTC by Igor20099

2023-05-24 05:18 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Сокеты открываются и закрываются согласно брифу
- Хорошая работа с датой и временем
- Раздельное хранение данных полученных по сокету

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- В проекте должен быть универсальный socketMiddleware. Нужно передавать объект с типами в вызов для повышения универсальности и независимости от внешних данных. Передавать `url` можно через payload с уже полными данными для отправки (токеном и тд). Посоветуйтесь с наставником
- `/all` ограничивает socketMiddleware под один вид эндпоинта, а нужно сделать универсальный миддлвар, который сможет любой эндпоинт указывать через `payload`.
- Каждый тип экшена должен быть вынесен в константу в папке actions, а потом его нужно использовать везде в коде. Это требуется для того, чтобы было одно место, где его можно изменить, подкорректировать, и не было шанса ошибиться в написании одной и той же строки в 2-3х местах. `export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS'`

**Можно лучше**
- Когда юзер нажал "Оформить заказ" лучше каким-то образом сообщить ему, что запрос ушел и нужно подождать. Например повесить лоадер на кнопку или показать модальное окно.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-05-24 05:18 UTC, andryxxa93 commented on src/components/app/app.jsx
> +       <Route path="/profile" element={<ProtectedRouteElement element={<ProfilePage />}/>} />
**Можно лучше**
Роуты желательно записывать в константы - так проще их менять и сложнее ошибиться при использовании в нескольких местах.

2023-05-24 05:18 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.js
> +  const isAuth = useSelector((state) => state.auth.isAuth);
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-05-24 05:18 UTC, andryxxa93 commented on src/services/middleware/socketMiddleware.js
> +        socket.onmessage = (event) => {
**Можно лучше**
Необходимо добавить проверку при получении сообщения от сокета. Eсли токен протух и приходит поле message 'Invalid or missing token' то его необходимо обновить через refreshToken.

2023-05-24 10:30 UTC, Igor20099 commented
> Здравствуйте! Проделана большая работа 👍
> 
> Что понравилось:
> 
> * Сокеты открываются и закрываются согласно брифу
> * Хорошая работа с датой и временем
> * Раздельное хранение данных полученных по сокету
> 
> Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.
> 
> Необходимо исправить:
> 
> * В проекте должен быть универсальный socketMiddleware. Нужно передавать объект с типами в вызов для повышения универсальности и независимости от внешних данных. Передавать `url` можно через payload с уже полными данными для отправки (токеном и тд). Посоветуйтесь с наставником
> * `/all` ограничивает socketMiddleware под один вид эндпоинта, а нужно сделать универсальный миддлвар, который сможет любой эндпоинт указывать через `payload`.
> * Каждый тип экшена должен быть вынесен в константу в папке actions, а потом его нужно использовать везде в коде. Это требуется для того, чтобы было одно место, где его можно изменить, подкорректировать, и не было шанса ошибиться в написании одной и той же строки в 2-3х местах. `export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS'`
> 
> **Можно лучше**
> 
> * Когда юзер нажал "Оформить заказ" лучше каким-то образом сообщить ему, что запрос ушел и нужно подождать. Например повесить лоадер на кнопку или показать модальное окно.
> 
> В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.
> 
> **Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.
> 
> Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью.
> 
> Удачных правок!

Нужно создать отдельный файл для констант или как?У меня константы в Actions как и рекомендуют

2023-05-25 08:45 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-05-26 08:39 UTC, merged